const cartActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_ALL_INGREDIENTS: "ADD_ALL_INGREDIENTS",
  ADJUST_INGREDIENT: "ADJUST_INGREDIENT",
  DELETE_INGREDIENT: "DELETE_INGREDIENT",
  CLEAR_CART: "CLEAR_CART",
};

export default cartActionTypes;
